### ISSUE TITLE
Adjust mouse sensitivity in 3rd person

### ISSUE THREAD

**Issue by marcosnc** [decentraland/explorer#1002]
We've received several complaints about the speed of the camera while in 3rd person.
Some people claim they got dizzy.

* Mouse sensitivity slider is inverted, 0 should be 1 and 1 should be 0.
* Difference between 0 and 1 should be way bigger
* We need to tweak the values so they work well with 3rd person mode
* We should increase the 3rd person camera easing time so it doesn't look "jittery" when rotating it.
* Maybe we should rename `mouse sensitivity` to `mouse aim speed`. (@eordano suggestion)

If with all those changes the mouse speed is hard to tweak, we can try to map the slider values to a curve.

**Comment by BrianAmadori** [comment]
For this issue, we should:

* Lower the sensitivity default value aiming to have a smooth 3rd person experience
* Tweaking the 3rd person camera easing so it doesn't look "jittery" when rotating it.

Next steps for another issue:
* Add new setting for first person/third person.
* Make the sensitivity slider scale with curved values instead of linear.
