### ISSUE TITLE
3rd Person Camera: adjust distance

### ISSUE THREAD

**Issue by xpalaum** [decentraland/explorer#115]
Let's try with The Witcher 3 camera distance to the avatar.
![witcher.jpg](https://images.zenhubusercontent.com/5d91dca0703cca0001efbe30/9206bdd9-d9fc-4bd2-a527-8dff41a0f611)

**Comment by AjimenezDCL** [comment]
This cannot be achieved. 

The reason this setup works in The Witcher is because they dont have a pointer. Ours game is controlled like an FPS and the pointer must be locked to the center of the screen, therefore having the pointer in the horizont line will provide you always the same point of view.

I'm gonna add support to change the field of view, maybe with that you can achieve something similar.
