### ISSUE TITLE
Settings: graphic quality affecting UI

### ISSUE THREAD

**Issue by RominaMarchetti** [decentraland/explorer#1232]
The UI must always be in high quality, independently from  the world.

**Comment by BrianAmadori** [comment]
The base resolution setting will always affect UI, and we can't remove the base resolution setting because the impact is high in low spec PCs. 

In any case we can change the default base resolution to be on `match 1080`. Maybe the actual issue is that we have the default on `match 720` and this is not acceptable. 

@RominaMarchetti I need your input on this comment.
