### ISSUE TITLE
Fix wearable-api CORS error in production

### ISSUE THREAD

**Issue by pravusjif** [decentraland/explorer#1443]
during Rarible's event I saw the following CORS problems in the console (many avatars weren't being displayed, maybe in part due to this?)

This is happening in produciton.

![chrome_UZYh9p1jAC.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/8c8149d7-acca-4cdb-9b5e-5182417ff86d)

![chrome_0dRpJvCTzd.png](https://images.zenhubusercontent.com/5d9200f4f58e25000108abac/94cb1fe1-b7fb-444d-9ca6-16f89870deea)

**Comment by BrianAmadori** [comment]
@nachomazzara mentioned me that these CORS errors most likely are masked 500 errors. So this is prolly a server side issue. We should sync with him if this happen again.

From our side, the proposed fix for this issue is to ensure error message displays when this happens. If this was already the case we should close it. @pravusjif

**Comment by nachomazzara** [comment]
Based on the current failures, seems to be an error when our Ethereum private node crashed. Will keep monitoring it

**Comment by pravusjif** [comment]
I'm closing this since it didn't happen again.
