### ISSUE TITLE
fix: entities with no transform appear at scene's 0,0

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/explorer#178]
We should at least hide the objects (maybe far away, as we do with the scenes while the renderer is off) until a real transform component data reaches the client.

**Comment by nearnshaw** [comment]
Implementing this is risky for existing scenes

Some scenes might be intentionally leaving models with no transform, and placing the meshes in the model relative to that position, so that they all fit in the scene.

Also, if an entity has another entity as a parent, it's sometimes completely avoidable to give it a Transform, as it takes the position of the parent, and sometimes you don't need to offset from there.

**Comment by AjimenezDCL** [comment]
@nearnshaw @BrianAmadori so shall we close this ticket? fromt Nico's comment I assume that the beahviour No-Transform = 0,0,0 is correct.

**Comment by nearnshaw** [comment]
I would say that yes, we should close it
changing this behavior could lead to existing content breaking, and I think it's intuitive enough as a default behavior
