### ISSUE TITLE
Interaction toast final design

### ISSUE THREAD

**Issue by BrianAmadori** [decentraland/explorer#220]
## Is this something you can **debug and fix**? 

Send a pull request! Bug fixes and documentation fixes are welcome. You can avoid the issue.

---

## Have an idea for a feature? 

* [ ] Post the feature request and tag it as "discussion". 
* [ ] Explain the motivation, the problem it fixes or the added value for the feature. The discussion about the feature should happen in the issue, and the code review in the PR.
* [ ] Write a check-list explaining the discrete elements to be developed.
* [ ] Explain how to validate/test the feature

---

## None of the above, create a bug report

Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the `Needs more information` label and close the issue until there is enough information.

* [ ] Provide a **minimal code snippet** / video example that reproduces the bug.
* [ ] Provide **screenshots** where appropriate
* [ ] Does this occur on chrome or firefox?
* [ ] Are you using Mac, Linux or Windows?
* [ ] Are you using a VR headset? Which one?

**Comment by pravusjif** [comment]
**How to test:**
1. Open the "Assets/Scenes/Test/Misc/PointerDownComponentTest.unity" scene
2. hit PLAY and approach the Lantern model (you have to get close due to the interaction distance)

**Prefabs where you should update the UI design (by double clicking them):**
(for now instead of having a configurable Text on the canvas we have separate icon prefabs for each button action type (Pointer, Primary, Secondary, Unknown), it was a tech lead's decision)
* Pointer action ICON prefab: /Users/pravus/GIT/explorer/unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InteractionHoverCanvas/Resources/PointerButtonHoverIcon.prefab
* Primary button action ICON prefab: /Users/pravus/GIT/explorer/unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InteractionHoverCanvas/Resources/PrimaryButtonHoverIcon.prefab
* Secondary button action ICON prefab: /Users/pravus/GIT/explorer/unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InteractionHoverCanvas/Resources/SecondaryButtonHoverIcon.prefab
* Unknown button action ICON prefab: /Users/pravus/GIT/explorer/unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InteractionHoverCanvas/Resources/UnknownButtonHoverIcon.prefab
* Hover canvas prefab: /Users/pravus/GIT/explorer/unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InteractionHoverCanvas/Resources/InteractionHoverCanvas.prefab

**Ping me if any question arises**
