### ISSUE TITLE
fix: chat wheel sensitivity

### ISSUE THREAD

**Issue by xpalaum** [decentraland/explorer#250]
Scrolling with the mouse wheel is way too slow. Change it to a speed that feels right.

Originally this included fixing the Scroll bar (point & drag), but we dropped it as it cannot be done without a re-implementation (see comment below).

**Comment by pravusjif** [comment]
I just implemented an increase in the scrollbar speed at https://github.com/decentraland/explorer/pull/323

The problem comes with the other part of this issue, we can't implement that fix until we **implement the chat window IN the client instead of using the UI of the SDK from kernel**, because the problem is with the behaviour we have in kernel for the moment we **unfocus the text input**, we hide everything there, that's why if we click in the chat window, but not in the text input, the whole chat window is hidden nowadays.

**Comment by xpalaum** [comment]
thanks.
not good news. some users will not realize they can scroll with mouse wheel (true personal story ;).

just for checking, what'd be a rough estimation of implementing chat window in the client? could we use an existing library instead of doing it our own from scratch?

in the meantime i will remove the chat scroll bar fix from this issue so you can close it.

**Comment by pravusjif** [comment]
We should:
- Remove kernel's "ChatWindows.ts" implementation that uses the SDK to render the chat in-client
- Implement the chat on client's side (one possible approach, not sure if feasible, would be to pause the unity editor in runtime, somehow copy the structures and gameobjects involved in the chat UI and then save them after stopping the play-runtime into a prefab or similar) and the pertinent scripts controlling the chat window and communicating with kernel.
- Ensure the chat window is not hidden when blurring/unfocusing **the text input**, and instead is hidden when unfocusing anything from the chat window (this way the scrollbar can be used)

I'm roughly guessing here but given the complexity of our systems this could take a dev's half or 1 sprint I think.

**Comment by xpalaum** [comment]
Thanks. I don't think we'll have bandwidth to do that for launch date.
