### ISSUE TITLE
tracking: user movement across scenes

### ISSUE THREAD

**Issue by xpalaum** [decentraland/explorer#300]
**Goal:**
Measure scene metrics (for ex: return rate, average time spent) and be able to report it to scene owners.

**How:**
We need to track when users change from one scene to the next.
- [ ] Add an extra parameter to move_to_parcel event. @dnul could you please define it?

**Comment by dnul** [comment]
depending on the content server api version:
* si usas la api vieja tenes que usar el scene_cid que se devuelve en la api
* si usas la api nueva tenes que usar el campo id

**Comment by dnul** [comment]
@moliva can we bring this one back? we'd need it for the open-data initiative

**Comment by moliva** [comment]
Sure! Let's prioritize this with @agusferreira possibly for next sprint.

**Comment by marcosnc** [comment]
Currently, we do not have a scene id being sent to Metabase in the move_to_parcel table.
However, we're sending the parcel coordinates for the from and to parcels, named OldParcel and NewParcel respectively.
Sending the scene id, won't add much more information, because that id changes on every scene change, as it's content-based.
For parcels' owners, it's more important to know the users went across their parcels than the version of the scene being deployed. 
On the other hand, using the parcel's coordinate and the timestamp it's easy to know which version of the scene was deployed at that time.
Based on all the previous points, I'm closing this issue as "Won't do".
