### ISSUE TITLE
Trigger areas not working on some scenes

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/explorer#429]
The following scenes have problems with their trigger areas in-world. These work in prevew. Everything else in the scene seems to work, it's just the trigger areas that are broken.

Toki Toki land, I can't collect coins:
https://explorer.decentraland.zone/branch/fix/ReportedCurrentSceneId/index.html?ENV=org&position=-5%2C-49

In the christmas plaza I can't trigger any of the messages that display text when I walk around. Same for the one that activates the floating platform.
https://explorer.decentraland.zone/branch/fix/ReportedCurrentSceneId/index.html?ENV=org&position=34%2C-107
In the quest of he alcoholic scarecrow, if I walk up to the scarecrow he should run away
https://explorer.decentraland.zone/branch/fix/ReportedCurrentSceneId/index.html?ENV=org&position=-8%2C-27

**Comment by pravusjif** [comment]
Be careful with the links you use, those 3 links are using a build in a branch (that has already been merged), we should always use zone to get the latest master branch changes:

* Toki Toki land is coin fetching is definetly broken, but going to old commits I can't find a moment when it worked, did it ever work? do we have the scene to check it out working in preview mode?
https://explorer.decentraland.zone/?ENV=org&position=-5%2C-49

* the messages in the christmas plaza seem to work just fine, I get the "smells like carrots" message normally: https://explorer.decentraland.zone/?ENV=org&position=34%2C-107

* in the quest... i can't find an old commit in which it works, same as in toki toki land, do we have the project to check it working in preview mode?
https://explorer.decentraland.zone/?ENV=org&position=-8%2C-27

**Comment by pravusjif** [comment]
By re-deploying the Toki Toki land without rotation (manually changed in the scene's code) the problem was fixed.

We should:
- Apply that workaround fix to the affected scenes ("the quest of the alcoholic scarecrow" we got doesn't run correctly in local)
- Create an Issue when we can reproduce the error with a newly created scene, possible bug triggers are:
* rotating the scene when deploying (thus having a version of the scene rotated, that's different than the local/exported scene (that's why it works fine in preview mode)
* somehow offsetting the scene or its base parcel when deploying (not sure how the user could achieve this)
