### ISSUE TITLE
Invisible entities have on-hover feebdack

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/explorer#740]
This is mostly evident with key smart items: after picking up the key, the on-hover feedback still says "pick up" where the key used to be.

This didn't happen before, as soon as the key was made invisible, the feedback went away. I'm quite sure that invisible entities in general aren't clickable, and so they should have no feedback.

In fact, for the "click area" smart item, we had to provide a fully transparent texture, but the entity had to be visible to be clickable.

This is happening in the key's code when it's picked up:
```
  hide(key: Entity) {
    if (this.isHidden(key)) return
    this.hiddenKeys.push(key)

    const gltfShape = key.getComponent(GLTFShape)
    gltfShape.visible = false
  }
```

I also tried adding this line to that function, but it changed nothing, the on-hover feedback is still there:
```
    gltfShape.isPointerBlocker = false
```

**Comment by pravusjif** [comment]
This "bug" keeps happening in interactions like the ones at Quest of the alcoholic scarecrow and Magic world, because in those cases the pointer event that triggers the interaction is in a separate entity than the rendered object... so in those cases rather than a bug is a misuse of the SDK/Smart items.

In places like the space office, after picking a keycard, the interaction is no longer available, as the bug has been corrected.
